# Goals for this project, and next steps:

Possible questions:
1. How does road

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
radar_points = pd.read_csv('Radar_Points.csv')
instances = pd.read_csv('Instances.csv')
runs = pd.read_csv('Runs.csv')

# Joining radar_points and instances

In [12]:
radar_data = radar_points.merge(instances, on=['global_instance_id', 'run_instance_id', 'parent_instance_id'])

In [13]:
radar_data

,radar_point_id,global_instance_id,driver_id,run_instance_id,parent_instance_id,timestamp,leader_vel,leader_accel,follower_vel,follower_accel,...,run_id,leader_radar,leader_veh_type,follower_radar,follower_veh_type,start_time,end_time,road_type,congestion,speed_limit
0,0,3002,3,2,2,00:05:48.291,23.432740,0.010000,26.432740,-1.255089,...,3,10,pc,1,pc,00:05:48.100,00:06:11.300,hw,u,50
1,1,3002,3,2,2,00:05:48.393,23.329850,-0.010000,26.229850,-1.209624,...,3,10,pc,1,pc,00:05:48.100,00:06:11.300,hw,u,50
2,2,3002,3,2,2,00:05:48.493,23.401880,0.000000,26.201880,-1.172918,...,3,10,pc,1,pc,00:05:48.100,00:06:11.300,hw,u,50
3,3,3002,3,2,2,00:05:48.592,23.247540,-0.030000,25.734138,-1.256701,...,3,10,pc,1,pc,00:05:48.100,00:06:11.300,hw,u,50
4,4,3002,3,2,2,00:05:48.693,23.247540,0.000000,25.883365,-1.170000,...,3,10,pc,1,pc,00:05:48.100,00:06:11.300,hw,u,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603517,603517,66037,66,37,37,00:53:13.818,22.024080,-0.550000,23.124080,-0.030000,...,66,0,pc,10,pc,00:52:49.580,00:53:14.260,hw,u,45
603518,603518,66037,66,37,37,00:53:13.918,22.108640,-0.523508,23.108640,-0.030000,...,66,0,pc,10,pc,00:52:49.580,00:53:14.260,hw,u,45
603519,603519,66037,66,37,37,00:53:14.017,22.201240,-0.453849,23.201240,0.000000,...,66,0,pc,10,pc,00:52:49.580,00:53:14.260,hw,u,45
603520,603520,66037,66,37,37,00:53:14.119,21.952060,-0.307216,23.052060,-0.020000,...,66,0,pc,10,pc,00:52:49.580,00:53:14.260,hw,u,45
603521,603521,66037,66,37,37,00:53:14.219,21.969079,-0.310159,23.067490,-0.010000,...,66,0,pc,10,pc,00:52:49.580,00:53:14.260,hw,u,45

In [16]:
radar_data.columns

Index(['radar_point_id', 'global_instance_id', 'driver_id', 'run_instance_id',
       'parent_instance_id', 'timestamp', 'leader_vel', 'leader_accel',
       'follower_vel', 'follower_accel', 'delta_dist', 'delta_vel', 'run_id',
       'leader_radar', 'leader_veh_type', 'follower_radar',
       'follower_veh_type', 'start_time', 'end_time', 'road_type',
       'congestion', 'speed_limit'],
      dtype='object')

In [18]:
radar_l_f = radar_data[(radar_data['leader_radar'] == 0) & (radar_data['follower_radar'] == 1)]
radar_l_f

,radar_point_id,global_instance_id,driver_id,run_instance_id,parent_instance_id,timestamp,leader_vel,leader_accel,follower_vel,follower_accel,...,run_id,leader_radar,leader_veh_type,follower_radar,follower_veh_type,start_time,end_time,road_type,congestion,speed_limit
2068,2068,3012,3,12,12,00:11:25.387,20.446640,0.184286,20.377122,0.206952,...,3,0,pc,1,pc,00:11:14.100,00:11:28.300,hw,u,40
2069,2069,3012,3,12,12,00:11:25.487,20.546640,0.150000,20.246640,0.120231,...,3,0,pc,1,pc,00:11:14.100,00:11:28.300,hw,u,40
2070,2070,3012,3,12,12,00:11:25.587,20.998637,-0.125933,20.610651,0.069344,...,3,0,pc,1,pc,00:11:14.100,00:11:28.300,hw,u,40
2071,2071,3012,3,12,12,00:11:25.686,20.729580,-0.145347,20.529580,0.070000,...,3,0,pc,1,pc,00:11:14.100,00:11:28.300,hw,u,40
2072,2072,3012,3,12,12,00:11:25.788,20.549530,-0.130000,20.549530,0.090000,...,3,0,pc,1,pc,00:11:14.100,00:11:28.300,hw,u,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588016,588016,64009,64,9,9,00:10:34.824,21.866410,-0.254651,21.866410,0.439489,...,64,0,pc,1,pc,00:10:19.430,00:10:41.680,hw,u,45
588017,588017,64009,64,9,9,00:10:34.923,21.375440,-0.102455,21.382276,0.419316,...,64,0,pc,1,pc,00:10:19.430,00:10:41.680,hw,u,45
588018,588018,64009,64,9,9,00:10:35.024,21.405474,-0.156169,21.405933,0.383969,...,64,0,pc,1,pc,00:10:19.430,00:10:41.680,hw,u,45
588019,588019,64009,64,9,9,00:10:35.125,21.058110,-0.320000,21.258110,0.340000,...,64,0,pc,1,pc,00:10:19.430,00:10:41.680,hw,u,45
588020,588020,64009,64,9,9,00:10:35.823,19.902510,-1.271153,20.547222,-0.537644,...,64,0,pc,1,pc,00:10:19.430,00:10:41.680,hw,u,45